spring:
  application:
    name: zipkin
  rabbitmq:
      host: rabbitmq
      port: 32771
      username: user
      password: password

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}